### ISSUE TITLE
Warning 53 (misplaced-attribute) on OCaml 5.2

### ISSUE THREAD

**Issue by mlemerre** [codex-semantics-library/patricia-tree#7]
I have the following error

```
145 | val highest_bit : int -> (int [@untagged]);;
                                      ^^^^^^^^
Error (warning 53 [misplaced-attribute]): the "untagged" attribute cannot appear in this context
```

I fixed those concerning the specialise tag (check that it is OK) but I am not sure how to fix those as they seem OK to me... I'm open for ideas!

**Comment by mlemerre** [comment]
This does not seem correct. The returned integer is not an OCaml integer, so I doubt that we can just drop the attribute.

**Comment by dlesbre** [comment]
OCaml wraps the function in that case, otherwise there would be a bug in the ocaml compiler.

See [the compiler explorer](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyah04tvXIrGqIgSHVmmAMLp6AVzZMQspwBkCJmwAOU8AI2xSEABmcgAHdCVieyZXDy8DBKS7IQCg0LYIqJ4rbBscphEiFlIiNM9vWWtsWxSqmqI8kPDImKtq2vqMkqUBzsDuwt6eAEordHdSVE4uNix3RgBqABVNgFJogBFN0dJ3Wz2tAEFN283sdSJI1npNwXRNkE3Aok2AWgOuE2EB%2BewArAAhAAC7mELGAwGwmHBhxm%2ByO%2BwATJjzPQAPrvPFhACeTz22KxOPY%2BPe5MxlyuTi4c3o3DB/G8vH46G4AHlnNSTgsltgsdE%2BOQiNpmXMANYgMFaQzcaT8NgKpWcnTkHlcfhKEBKqVcHRzOCwFAYHD4YhkSjUOiMVgcbgSwTCMQSTgyOTCZRqTQmvQgTGGYymXGlcopRxMFxuBohsHkfwTApFEPxRLJIRDbyY5NZHNMLrp3qh5qtITtQYJjIFqMtCo18b5HpRCtjPNJ/odUvtkNzJTC5bcNaYDai3ZfJLAfbXO6bABuEje6A%2BXx%2B/0B32EDKc6OOp3ORAZi4eT1ILzXG93vwB0SBIL3kJhcIRSJRaIOxzpuIJ65EqS2B0pS/60ti%2B5xsyypcOy5BatyfIChYQqLMsYqYvwxqmnMSDYCwOBRBALIqmqGoIdKOrcPqhqStKMxyj4AAcAB0ABsPAAOzSJx0RgtImLRNIXElKyXDRByVG6thDHkOayAgIQNA0PatDyJ6kg%2Bu6igqBoVH0EgBpiUZyk0EQxJxJwSqGSojykCw6BxBUNHkKQRmZu5ShmRZVl0V5F4OU5Ll6qRcFSUG1FcIcBAqZsABqBDYAA7pEmzqMx7F/Ox0ibGY1LBZs0isTIrFaMuSjpZl2W5flFiFcVpXajhMEQJa6BsHEDCRGpGCdd1UR1fQ0gyEqjqXgaEBhFRYSBDUxKuvws2sKQxK8mEuhNot5B9Rwwi8kw9ALZFOBhO4wACvQ9AGly5A4Gw4aSCdBCkE2BBLtgN3ag8LTuE820/GUBkEGEDmra4OBUUQpAEOqt0faQYSJNghzYA9Jj0IEoBBnMNBGMASiJSlvJWZyboaeIWmyDp/r6ZF%2BhieGIBDYYIMGpAczBSkN3cgjMM4OzJGNlW3gQE43YlKmbZTMUWbZCkEty8W/YywYlbNl2dbeCMZRvdWYwqxmIya%2Bk2u9rUhvTEOI7emF8GIVFVVZTleW4g1JXFeVEA2iQpBirMsk4/J7X9YwFBUBAfVdWHzO4iN0hjQwE3UNNkXLfN23p6t62bbY227cwRAHUdVGnedl3Xdt92PSs2qEK9rQfV9/A/agf0rBKgPidqmOg/NEO19hMNwxKCNIyoqPo8AmMmHJePwoTSXJSTzDbTpmnetT8i04G2r6KGRizyzveC5zznc656B8wQAvwEOusi7G8amwYUuTEbSsVIrRYVJbsvq20E2iYdbRn1n2NMA5jYdEVqMcB0sjbW3QpwTEdsIral1E7GqrsCrOSKh7MqwIfZkEwjMQOuFyDyjBDwVi0RmIFloTlMEXF2JgkxAATlkOJVUlFIoySsAYFqjFYJYR4eg1ygi5gIySA4aQQA%3D) for differences between compiling with/without a constrained signature.

Another possible fix is to expose the `external` in the `mli` directly. I'd rather hide the implementation though.

**Comment by mlemerre** [comment]
Actually, the function is used only for testing; moreover, changing the implementation would retain source-level compatibility. I think exposing the external would be safe.

**Comment by dlesbre** [comment]
Done.
